### ISSUE TITLE
React Failed to compile

### ISSUE THREAD

**Issue by Drethic** [stoplightio/json-schema-viewer#123]
## Describe the bug

After creating a fresh react app with `create-react-app` I added json-schema-viewer with yarn, imported it per the README, and dropped in the example block updating schema to be an import of a json schema.  When I start the react app I get this error:

```
Failed to compile.

./node_modules/@stoplight/json/index.es.js
Attempted import error: 'ORDER_KEY_ID' is not exported from '@stoplight/ordered-object-literal' (imported as 'h').
```

## To Reproduce

1. Create a fresh create-react-app with `npx create-react-app schema-viewer`
2. Install json-schema-viewer `yarn add @stoplight/json-schema-viewer`
3. Update App.js to this:
```js
import './App.css';
import { JsonSchemaViewer } from "@stoplight/json-schema-viewer";
import * as schema from './schemas/battery.json';

function App() {
  return (
    <div className="App">
      <JsonSchemaViewer
        name="Battery Model"
        schema={schema}
        expanded={true}
        hideTopBar={false}
        emptyText="No schema defined"
        defaultExpandedDepth={0}
      />
    </div>
  );
}

export default App;
```

Battery Schema
```json
{
	"type": "struct",
	"fields": [{
		"name": "battery_status",
		"type": "integer",
		"nullable": true,
		"metadata": {}
	}]
}
```

## Expected behavior

The module to compile and render in React.

## Additional context

**Screenshots**

**Environment (remove any that are not applicable):**
 - Library version: 3.0.1
 - OS: OSX Big Surr
 - Browser: Chrome  89.0.4389.90
 - Platform: web

**Comment by mpodlasin** [comment]
Hey @Drethic could you share with us what version of @stoplight/ordered-object-literal package you have in our node_modules? :thinking:

**Comment by Drethic** [comment]
This is from it's package.json:
```
  "name": "@stoplight/ordered-object-literal",
  "version": "1.0.1",
```

**Comment by mpodlasin** [comment]
If you update to 1.0.2 your problem should go away. :)

Let me know how it went.

**Comment by Drethic** [comment]
I ran yarn upgrade and verified `@stoplight/ordered-object-literal` incremented to 1.0.2.  After starting I am now getting a new compile error:
```
Failed to compile.

./node_modules/@stoplight/json-schema-viewer/index.es.js
Module not found: Can't resolve '@stoplight/markdown-viewer' in '/path/to/project/schema-viewer/node_modules/@stoplight/json-schema-viewer'
```

To ensure my node_modules weren't corrupt from the upgrade I removed the whole node_modules directory, reran `yarn install`, verified ordered-object-literal was still 1.0.2, and after starting the react app the markdown-viewer error was still present.

**Comment by mpodlasin** [comment]
Hmm I see. I'll take a look then. Hang in there, I'll come back to you.

Sorry this took so much time BTW.

**Comment by mpodlasin** [comment]
I installed CRA, then `@stoplightio/json-schema-viewer` and then peer dependencies from the package.json: `mobx`, `@stoplightio/markdown-viewer` and `@stoplight/ui-kit` and it works.

I had a fresh install, so `1.0.1` vs `1.0.2` of `ordered-object-literal` didn't affect me, because I instantly got the newer version.

So please try to replicate your setup. 

If it still fails, please make a repo of your failing project and share it with me here.

If you can't share that project, please try to create a fresh one and replicate the same problem. Otherwise it will be tricky for me to help. :pray:
