### ISSUE TITLE
Select looks weird

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/json-schema-viewer#136]
## Describe the bug

Select for choosing type options is weirdly placed and in general doesn't look right - probably some kind of regression.

## To Reproduce

Visible on default story in storybook

## Expected behavior

Looks closer to what is present in the designs

**Screenshots**
![Screenshot from 2021-04-19 15-54-29](https://user-images.githubusercontent.com/7916523/115252931-34b76800-a12c-11eb-90bd-0b4130c4a8f9.png)

**Comment by marcelltoth** [comment]
Not reproducible anymore. There is some weirdness going on with that Select still, will be filed separately.
