### ISSUE TITLE
Promote JSV v4 to stable

### ISSUE THREAD

**Issue by marcelltoth** [stoplightio/json-schema-viewer#141]
As agreed, we can mark JSV v4 as stable, releasing 4.0.0 and tagging it _latest_.

**Comment by marcelltoth** [comment]
Do we want to hold off with this until mosaic is stable? @mallachari @P0lip

**Comment by P0lip** [comment]
If there are not breaking changes coming up in Mosaic that would affect JSV, I believe we can make JSV v4 stable.

**Comment by mallachari** [comment]
Should be good to go. Nothing breaking that I can see
