### ISSUE TITLE
When using oneOf and the type is an object the description does not display

### ISSUE THREAD

**Issue by ben-leonard-tbol** [stoplightio/json-schema-viewer#250]
## Context
Im attempting to use a oneOf with many objects which I want the description to display under the dropdown but it does not work when the type is object. It does work for boolean etc. (FYI Paid Subscription for Stoplight)

## Current Behavior
Adding a description to an object type in a oneOf does not display the description. Doing the same for boolean does display the description

## Expected Behavior
I expect when select an object type from the oneOf dropdown to be able to see the description for the object

## Possible Workaround/Solution
None

## Steps to Reproduce
1. Go to https://stoplightio.github.io/json-schema-viewer/?path=/story/combiners--one-of-multi&globals=backgrounds.grid:false
2. Add raw json below
`{
  "title": "a",
  "oneOf": [
    {
      "title": "b",
      "type": "object",
      "properties": {
        "c": {
          "title": "d",
          "type": "string"
        },
        "e": {
          "title": "e",
          "type": "string"
        }
      },
      "description": "b description"
    },
    {
      "title": "f",
      "type": "boolean",
      "description": "f description"
    },
    {
      "title": "g",
      "oneOf": [
        {
          "title": "h",
          "type": "string"
        },
        {
          "title": "l",
          "type": "object",
          "properties": {
            "foo": {
              "title": "k",
              "oneOf": [
                {
                  "title": "m",
                  "type": "string"
                },
                {
                  "title": "o",
                  "type": "object",
                  "properties": {
                    "foo": {
                      "type": "string"
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  ]
}`
3. Select f from dropdown and you will see f description
4. Select b from dropdown and you will **not** see b description

## Environment
First noticed through stoplight elements but validated on storybook todays date https://stoplightio.github.io/json-schema-viewer/?path=/story/combiners--one-of-multi&globals=backgrounds.grid:false

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Version 120.0.6099.234
- Operating System and version (desktop or mobile): Mac 14.2.1
- Link to your environment/workspace/project: replicated on storybook but paid subscription https://thebankoflondon.stoplight.io/

**Comment by ben-leonard-tbol** [comment]
@falsaffa @P0lip any help / guidance on this issue would be appreciated

**Comment by mnaumanali94** [comment]
@ben-leonard-tbol Can you please create a support case for this using the contact support button in your workspace. We take stoplight workspace issues there. 🙏🏼
