### ISSUE TITLE
Suggestion: ability to change the way validations are displayed

### ISSUE THREAD

**Issue by reorx** [stoplightio/json-schema-viewer#31]
In versions before 1.1, and also the version currently used on next.stoplight.com, validations will be expanded in the field definition after clicking the row:

![image](https://user-images.githubusercontent.com/405972/59915702-da75ef00-944f-11e9-8ed8-86139c467151.png)

In 2.X however, validations are displayed in a tooltip when hovering on the rightmost hint, moving away the mouse will let it disappear, and clicking the hint cannot make it display permanently.

![image](https://user-images.githubusercontent.com/405972/59916359-8409b000-9451-11e9-9faa-52e15ae0880e.png)

Obviously this is a major design change in 2.X, the philosophy of this change I suppose, is to avoid changing the height of the field row, so that the look and feeling is more solid than before.

This is OK as a new feature, for many cases where the schema is simple, this makes the viewer looks cleaner. But when the schema contains a lot of validations, such as the images above, reader needs a constant view of multiple fields expanded with their validations. Compare the two images above, it's obvious to find the first one is much more informative than the second one. Imagining the reader split the screen in left and right, left is the json schema viewer document, right is the editor for coding, if the validations cannot be permanently expanded, he has to move mouse a lot to open the tooltip of different fields, which could be very interruptive for the work.

In general, I suggest to make how validations are displayed to be a configuration, for example, it could be called `validationsDisplayMethod`, and has two enum values: `TOOLTIP` and `INLINE`, let the user to choose the one that suit best for the situation.

**Comment by marbemac** [comment]
Valid points. This one is a bit trickier. There are a couple of reasons - the first is as you described, in the simpler use case the UI is cleaner. The second reason is more complicated - JSV v2 uses list virtualization to improve performance when rendering gigantic schemas. However, list virtualization comes with a cost - it makes variable height rows more complicated. We can investigate variable sized row heights, but likely won't be able to get to this in the short term as we're working towards some major release in next couple of months.

**Comment by reorx** [comment]
I understand, sometimes design compromises to code. Currently I'm using the 1.0.3 version with the dynamic row height ability, it's a tough choice to abandon the newest version which has a lot of improvements I love. Anyway, keep up the good work, JSV is the best JSV by far, thanks for contributing it to the community!

**Comment by philsturgeon** [comment]
v3.0 has changed a lot and v4.0 is going to look a whole lot better. Virtualization is gone and it's got a new design, so let us know what you think.
