### ISSUE TITLE
Changing observed observable values outside actions is not allowed

### ISSUE THREAD

**Issue by lottamus** [stoplightio/json-schema-viewer#42]
Platform Studio is complaining that we're changing an observed observable's value outside an action.

![image](https://user-images.githubusercontent.com/7423098/62413420-73ae2e80-b5d4-11e9-8883-808a25d24708.png)

![image](https://user-images.githubusercontent.com/7423098/62413428-86c0fe80-b5d4-11e9-9ac4-d4cf98f5c3ab.png)

**Comment by P0lip** [comment]
Should be fixed in https://github.com/stoplightio/json-schema-viewer/issues/42
