### ISSUE TITLE
Rendering array of allOf only works when in a schema with another allOf property

### ISSUE THREAD

**Issue by lottamus** [stoplightio/json-schema-viewer#50]
**Describe the bug**

We have the capability of rendering an array of allOf. You can see this via the "working schema" below because I'm including another allOf property. However it fails to render whenever that extra allOf property is removed as you can see via the "broken schema".

**To Reproduce**

Working schema:

```json
{
  "title": "Test",
  "type": "object",
  "properties": {
    "array-all-objects": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "properties": {
              "foo": {
                "type": "string"
              }
            }
          },
          {
            "properties": {
              "bar": {
                "type": "string"
              }
            }
          }
        ],
        "type": "object"
      }
    },
    "all-objects": {
      "allOf": []
    }
  }
}
```

![image](https://user-images.githubusercontent.com/7423098/64307947-4d760880-cf5d-11e9-96af-1fb3f5abf851.png)

Broken schema:

```json
{
  "title": "Test",
  "type": "object",
  "properties": {
    "array-all-objects": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "properties": {
              "foo": {
                "type": "string"
              }
            }
          },
          {
            "properties": {
              "bar": {
                "type": "string"
              }
            }
          }
        ],
        "type": "object"
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/7423098/64307579-28cd6100-cf5c-11e9-9eb7-744fc9e18be5.png)

**Expected behavior**

The allOf is resolved and nested inside the array as seen in the working schema example.

**Comment by marbemac** [comment]
I think this is causing several downstream issues - including at amadeus. Can you prioritize this one @P0lip?
