### ISSUE TITLE
Support JSON Schema draft-7, 2019-09, and 2020-12

### ISSUE THREAD

**Issue by Relequestual** [stoplightio/json-schema-viewer#56]
**User story.**
As a developer, I can visualise new JSON Schema, so that I can work with OAS 3.2 (maybe).

**Describe the solution you'd like**
Suport changes from daft-7 and 2019-09

**Additional context**
JSON Schema core team - Thank you for your donation.
I want to try make this happen =D

**Comment by P0lip** [comment]
@Relequestual 
Thanks! Happy to see you here.
Heads up - at the moment json-schema-viewers supports (mostly) Draft 4 and perhaps some features OAS-flavored schema (that kind OAS kind-of JSON schema format, whatever it's called :sweat_smile:).
To improve general UX, we are quite lenient and try our best to infer types, etc.
Last but not least, we merge `allOf` by default using [json-schema-merge-allof](https://www.npmjs.com/package/json-schema-merge-allof).
Most of schema processing can be found in [src/utils/renderSchema.ts](  https://github.com/stoplightio/json-schema-viewer/blob/master/src/utils/renderSchema.ts)

Shoot me a question if you have any!

**Comment by Relequestual** [comment]
In terms of the merging `allOf`. The library...

> For meta keywords like title, description, $id, $schema, default the strategy is to use the first possible value if there are conflicting ones. So the root schema is prioritized. This process possibly removes some meta information from your schema. So it's lossy. Override this by providing custom resolvers.

Yikes. Please DO NOT do this. This is drastically wrong.
It also flies in the face of draft `2019-09` annotation collection (which is the embodyment of how annotations should work / be used).

I strongly advise you look to avoid doing this ASAP.
I would guess that most users do not run into problems with this, but any complex set of schemas will have issues in terms of using `$id` and `$ref`.

**Comment by philsturgeon** [comment]
@Relequestual we're picking this back up. We've had a lot of chats internally about getting allOf right, and I'm starting to wade into the fun world of assertions vs annotations, and annotation collection! 

We'll tackle this as part of the OAS3.1 work.

**Comment by philsturgeon** [comment]
There’s lots of work to be done around modern draft support and annotations but that’s all a bit much for one issue. The work will come as and when we get the various bits done, so I’ll close this down. Thanks for the tips Ben!
