### ISSUE TITLE
Option to configure resizing behavior

### ISSUE THREAD

**Issue by carlo-quinonez** [stoplightio/json-schema-viewer#67]
As a user, I'd like to see the webpage content resize to fit the length of the schema.

It would be great if we could pass in a prop to modify the AutoSizer behavior. In the dev tools, I get the desired behavior Iif I set the `disableHeight` prop for the AutoSizer.

I'd do this myself, but the AutoSizer component is part of the `@stoplight/tree-list` module which is a private repo. Can that repo be made public?

**Comment by carlo-quinonez** [comment]
I'm still a new to React, so I'd really appreciate any tips on how I can control the behavior of AutoSizer from my code. Even a pointer in the right direction to get me started...

BTW - great work on Stoplight Studio...

**Comment by P0lip** [comment]
Hey @carlo-quinonez 
My sincere apologies for such a delayed response.

We are not planning to make stoplight/tree-list public yet, but I can totally add a possibility to control `disableHeight`.
Would that meet your needs?

**Comment by carlo-quinonez** [comment]
@P0lip  A simple option to control `disableHeight` would be perfect.

**Comment by P0lip** [comment]
@carlo-quinonez you got it. I'll let you know once it's out.

**Comment by P0lip** [comment]
Actually, now that I think of the issue, I think it might be even doable right now, without `disableHeight` option.
To better understand the problem, could you create a small demo showcasing the case you deal with? You can use [codesandbox](https://codesandbox.io/) or something similar.

**Comment by carlo-quinonez** [comment]
I'm not able to get the component working in the [codesandbox](https://codesandbox.io/s/json-schema-viewer-autosizer-828o7).

I added all the missing dependencies (@stoplight/{ui-kit,tree-list,markdown-viewer} and mbox}, but I still see errors and the render shows the emptyText property instead of the schema . Do you have a second to take a look and see what's wrong?

**Comment by carlo-quinonez** [comment]
As far as the use-case, here's a screenshot of the documentation site we maintain.

![image](https://user-images.githubusercontent.com/53790047/78597124-cb570680-7801-11ea-9db5-8cc2028964e1.png)

I hack the AutoSizer setting by including a copy of the `@stoplight/ui-kit` module and changing the AutoSizer default for disableHeight to `true`. This will obviously break a lot of other things down the road, but it works for now...

If I don't use my hacked version of `@stoplight/ui-kit`, I get this displayed instead:

![image](https://user-images.githubusercontent.com/53790047/78597456-68b23a80-7802-11ea-93e1-f3cbc423ef79.png)

**Comment by P0lip** [comment]
@carlo-quinonez I see.
Does the parent have any explicit height? It needs to have some height in order for `disableHeight=true` to work.
In any case, I'll sneak `disableHeight` option in, so you should be able to use once JSV v3 is out.
I'm glad you found a workaround for the time being.

**Comment by carlo-quinonez** [comment]
Thank you @P0lip

**Comment by P0lip** [comment]
@carlo-quinonez try the very latest beta - it does not come with autosizer at all. 
This should meet your needs.

**Comment by carlo-quinonez** [comment]
Thank you, but there's no publically available package that meets the `@stoplightio/ui-kit` peerDep of `>3`. I'll try it with the latest available version of `@stoplightio/ui-kit` and will let you know how it goes...

**Comment by P0lip** [comment]
> Thank you. I had to do a little sleuthing to figure out the correct versions for my package.json. BTW - neither @blueprintjs/core nor @blueprintjs/icons are listed as a regular or peer dependency anywhere although they are required.

Good find. I'll add these.
Glad it worked for you!

**Comment by P0lip** [comment]
Since the issue is resolved, I'll mark this as closed.
Should you have any further concerns, feel free to reach out.
