### ISSUE TITLE
Handle if `null` in a combiner like `allOf`, `anyOf`, `oneOf`

### ISSUE THREAD

**Issue by marbemac** [stoplightio/json-schema-viewer#70]
**Describe the bug**

If there is somehow a null or otherwise non object value in the combiner array, json schema viewer will completely fail.

**To Reproduce**

<img width="871" alt="Screen Shot 2020-03-25 at 4 50 21 PM" src="https://user-images.githubusercontent.com/847542/77588906-c072ac80-6eb8-11ea-8738-949e868bf03b.png">

<img width="660" alt="Screen Shot 2020-03-25 at 4 47 39 PM" src="https://user-images.githubusercontent.com/847542/77588794-902b0e00-6eb8-11ea-8fad-394eb1f26c69.png">

**Expected behavior**

Render as normal, skipping the invalid values (I bet it fails for `true`, `null`, etc - anything that's not an object) - we'll catch this issue in spectral etc to report to the user.

**Comment by P0lip** [comment]
@marbemac `oneOf` and `anyOf` are handled just fine.
The problem with `allOf` is that it undergoes the merging process and json-schema-merge-allof does not really aims to support invalid schemas.

**Comment by P0lip** [comment]
I'll fix it.

**Comment by P0lip** [comment]
Fixed in https://github.com/stoplightio/json-schema-merge-allof/commit/b31adac3d0110f15e04af2d8d456280948768001

**Comment by P0lip** [comment]
Released as beta.9.
