### ISSUE TITLE
Handle local references better

### ISSUE THREAD

**Issue by marbemac** [stoplightio/json-schema-viewer#71]
**Describe the bug**

When there are local references, they're not all expandable (not sure if this is array property type problem or not though).

**To Reproduce**

1. Try rendering the schema below with JSV

```yaml
title: Email Message
type: object
x-tags:
  - Email
properties:
  fromAddress:
    $ref: '#/properties/another'
  toAddresses:
    type: array
    items:
      $ref: '#/properties/another'
  ccAddresses:
    type: array
    items:
      $ref: '#/properties/another'
  bccAddresses:
    type: array
    items:
      $ref: '#/properties/another'
  another:
    title: Email
    type: object
    x-tags:
      - Email
    description: An email object
    properties:
      category:
        type: string
      address:
        type: string
```

**Expected behavior**

- [x] `toAddresses`, `ccAddresses`, and `bccAddresses` should be expandable similar to how the `another` property is.
- [x] I don't know that we need to show local $refs (as seen in screenshot below in `fromAddress` property)? @P0lip what do you think?
- [x] Any particular reason for the extra nested object in the `fromAddress` property below? The `another` property is much nicer. cc @P0lip because I think you might have done the original implementation here.
- [x] The array properties `toAddresses`, `ccAddresses`, and `bccAddresses` should have type `array[object]`, or `array[#/propertiesanother]` if we're keeping the local refs showing. One other thought is that we could drop the `array` word there, and go with syntax like `[object]`, `[number]`, etc.

**Screenshots**

<img width="672" alt="Screen Shot 2020-03-25 at 9 19 52 PM" src="https://user-images.githubusercontent.com/847542/77603621-861c0600-6ede-11ea-98c6-d5f96a9c5c9a.png">

**Comment by P0lip** [comment]
>  toAddresses, ccAddresses, and bccAddresses should be expandable similar to how the another property is.

Yeah, this indeed a bug.

>  I don't know that we need to show local $refs (as seen in screenshot below in fromAddress property)? @P0lip what do you think?

I think it may be helpful if you cannot expand ref for whatever reason. In such case, you'd be able to see what the target of your $ref actually is.

> Any particular reason for the extra nested object in the fromAddress property below? The another property is much nicer. cc @P0lip because I think you might have done the original implementation here.

This is needed. Initially we displayed only properties, but this is simply wrong, since we do reference the whole object, not just its properties. This lead to a few subtle bugs, i.e. no validations, etc.

**Comment by marbemac** [comment]
> This is needed. Initially we displayed only properties, but this is simply wrong, since we do reference the whole object, not just its properties. This lead to a few subtle bugs, i.e. no validations, etc.

Hmm - anything other than the validations edge case? How often will that validation case be hit, e.g. only in limited situations?

Basically it makes the viewer more confusing when an object has a bunch of array[object] props inside of it - real world models. Each instance adds a whole extra rendering level. Was nicer before IMHO, but I'm not sure if the thing this was fixing is really important or not.

**Comment by P0lip** [comment]
> Was nicer before IMHO, but I'm not sure if the thing this was fixing is really important or not.

It was nicer, but also broken in certain circumstances, plus it made the implementation more complex.
In any case, if you really do want to get rid of the extra flattening level, I'm down for doing it - will just need to be cautious not to break existing scenarios.

**Comment by mallachari** [comment]
@marbemac @P0lip should we close this one or is there still something left to do/discuss?

**Comment by P0lip** [comment]
I think there is one item left to be done, but it's not listed here.
It'd be great to have `title` displayed instead of $ref path.
I can do it later this week, no worries.
