### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by Shevsky** [stoplightio/json-schema-viewer#73]
**Describe the bug**
When trying to rendering any schema, I've got an Uncaught TypeError: Class extends value undefined is not a constructor or null. I see warnings like this:

> "export 'Tree' (imported as 'r') was not found in '@stoplight/tree-list'
> "export 'TreeState' (imported as 'a') was not found in '@stoplight/tree-list'
> "export 'isParentNode' (imported as 't') was not found in '@stoplight/tree-list'

Is it a problem with webpack config?

v3.0.0-beta.11

**Screenshots**
<img width="790" alt="Снимок экрана 2020-04-07 в 13 32 40" src="https://user-images.githubusercontent.com/9802080/78647629-4983dd80-78d4-11ea-86f2-85052ebbced5.png">

**Comment by P0lip** [comment]
@Shevsky Hey!
Yeah, this seems like an issue with your Webpack config.
Mind sharing it?

**Comment by Shevsky** [comment]
That's my webpack configuration file:

`const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const autoprefixer = require('autoprefixer');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const TSLintPlugin = require('tslint-webpack-plugin');
const webpack = require('webpack');

const path = require('path');

function getNodeEnv() {
    const env = process.env.NODE_ENV;
    if (!env) {
        throw new Error('No NODE_ENV specified, break');
    }
    return env;
}

const isStandBuild = getNodeEnv() !== 'local';

const scssModuleRegex = /\.module.(s(a|c)ss)$/;

const PostCssLoader = {
    loader: require.resolve('postcss-loader'),
    options: {
        // Necessary for external CSS imports to work
        ident: 'postcss',
        plugins: () => [
            require('postcss-flexbugs-fixes'),
            autoprefixer(),
        ],
    },
};

const miniCssLoader = {
    loader: MiniCssExtractPlugin.loader,
    options: {
        publicPath: '/'
    }
};

function getStyleLoaders(shouldResolveUrls) {
    return [
        isStandBuild ? miniCssLoader : 'style-loader',
        {
            loader: 'css-loader',
            options: {
                url: shouldResolveUrls
            }
        },
        PostCssLoader
    ];
}

const DefaultStyleLoaders = getStyleLoaders(true);
const NoUrlsStyleLoaders = getStyleLoaders(false);

module.exports = {
    mode: isStandBuild ? 'production' : 'development',

    entry: [
        path.resolve('node_modules/tslib/tslib.js'),
        path.resolve('src/index.tsx')
    ],

    output: {
        path: path.resolve('build'),
        filename: 'static/[name].[hash:8].js',
        libraryTarget: 'umd',
        globalObject: 'this'
    },

    optimization: {
        minimize: isStandBuild
    },

    resolve: {
        extensions: ['.tsx', '.ts', '.js', '.jsx', '.styl'],
        modules: ['node_modules', path.resolve('src')],
        alias: {
            assets: path.resolve('src', 'assets')
        }
    },

    module: {
        rules: [
            {
                test: /\.tsx?$/,
                include: path.resolve('src'),
                exclude: /node_modules/,
                use: 'awesome-typescript-loader'
            },
            {
                test: /\.jsx?$/,
                include: path.resolve('src'),
                use: 'babel-loader'
            },
            {
                test: /.*\.icon\.svg/,
                include: path.resolve('src'),
                use: 'raw-loader?./[path][name].[ext]'
            },
            {
                test: [/\.(png|gif|jpe?g?)$/, /^((?!icon).)*\.svg/],
                use: 'file-loader?name=assets/[path][name].[ext]&context=.'
            },
            {
                test: scssModuleRegex,
                exclude: /node_modules/,
                use: [
                    'style-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            localsConvention: 'camelCase',
                            modules: {
                                mode: 'local',
                                localIdentName: '[name]__[local]___[hash:base64:5]'
                            },
                            url: true,
                            sourceMap: true
                        }
                    },
                    'sass-loader'
                ]
            },
            {
                test: [/\.scss$/, /\.sass$/],
                exclude: [scssModuleRegex],
                use: [
                    ...DefaultStyleLoaders,
                    'sass-loader',
                ],
            },
            {
                test: /\.styl$/,
                use: [
                    ...DefaultStyleLoaders,
                    'stylus-loader'
                ]
            },
            {
                test: /\.css$/,
                exclude: /node_modules/,
                use: DefaultStyleLoaders,
            },
            {
                test: /\.css$/,
                include: /node_modules/,
                use: DefaultStyleLoaders
            },
            {
                test: /semantic-ui-css\/.*\.(eot|ttf|woff2?|svg)$/,
                use: 'file-loader?name=assets/[name].[contenthash].[ext]&context=.'
            }
        ]
    },

    plugins: [
        new CopyWebpackPlugin([
            {
                from: path.resolve('public'),
                to: path.resolve('build')
            }
        ]),
        new HtmlWebpackPlugin({
            template: 'public/index.html',
            filename: 'index.html',
        }),
        new MiniCssExtractPlugin({
            chunkFilename: 'static/[name].[contenthash:8].css',
            filename: 'static/[name].[contenthash:8].css'
        }),
        new webpack.HotModuleReplacementPlugin(),
        new TSLintPlugin({
            files: ['src/**/*.ts?(x)'],
            project: 'tsconfig.json',
            typeCheck: true,
            waitForLinting: false
        })
    ],

    devServer: {
        contentBase: path.resolve(__dirname, '..'),
        hot: true,
        port: 4000,
        historyApiFallback: true,
        overlay: {
            errors: true,
            warnings: false
        }
    },

    performance: {hints: false}
};
`

**Comment by P0lip** [comment]
Perhaps try setting an alias for `@stoplight/tree-list`.
Tree-list is distributed with both cjs and ejs bundles. You'll find the file names under `node_modules/@stoplight/tree-list`.

**Comment by Shevsky** [comment]
Thanks, I tried this and it didn't solve the problem :( But I executed a package manager install command (yarn) in `project/node_modules/@stoplight/json-schema-viewer` directory and it works! Not sure if that's the correct solution ¯\_(ツ)_/¯
