### ISSUE TITLE
Empty contents of TreeList

### ISSUE THREAD

**Issue by Shevsky** [stoplightio/json-schema-viewer#74]
**Describe the bug**
I just created a new project using Create React App, installed latest stable `json-schema-viewer@2.12.0`, and there is no contents in DOM when I tried to show an json schema.

**Screenshots**
<img width="716" alt="Снимок экрана 2020-04-13 в 11 46 15" src="https://user-images.githubusercontent.com/9802080/79098986-95270300-7d7c-11ea-8dc9-3f4cd6f8d730.png">

**To Reproduce**
This is a project with example: [JsonViewerReactTest](https://github.com/Shevsky/JsonViewerReactTest/)

Seems like an issue with service worker, but I really don't understand what am I doing wrong :/

**Comment by AlmondQ** [comment]
same issue :( have you solved this yet?

**Comment by Shevsky** [comment]
still not solved :C

**Comment by philsturgeon** [comment]
We've pretty much rewritten JSV and removed the tree list requirement, replacing it with our own. If v3.0 didn't fix it, v4.0 beta will, so give it a go and chuck us a PR if you find a bug! Thanks :)
