### ISSUE TITLE
Simplest means of using the viewer

### ISSUE THREAD

**Issue by trubens71** [stoplightio/json-schema-viewer#79]
Question: Is this viewer hosted in a publicly available instance? I'd just like to be able to visualise a schema I am developing, to help with the review process. I don't see it as a feature within stoplight studio. Alas I don't have any knowledge of React so the documented Usage isn't much for me to go on! Apologies for what I'm sure is a dumb question.

**Comment by P0lip** [comment]
@trubens71 
We are working on [share view](https://portal.productboard.com/fljngg9hcw9knfsnwmtyzgva/c/8-share-readonly-view-of-a-studio-project-with-others) in Stoplight Studio.
It seems to me like this is exactly what you are looking for?
It's not out yet, but we are on it!

> Apologies for what I'm sure is a dumb question.

Not at all. No question is dumb. :slightly_frowning_face:

**Comment by P0lip** [comment]
Alternatively, you could also publish your docs directly from Stoplight Studio 
![image](https://user-images.githubusercontent.com/9273484/84707067-54a35b80-af5e-11ea-9859-ef30407fd44e.png)

**Comment by trubens71** [comment]
Thanks for getting back to me. Yes I can now see that publish makes the form view publicly available. However it seems that my expectation and question were not aligned. I'm looking for a way to graphically visualise a schema, i.e. a tree-like expanding view that allows a reviewer to explore a schema definition, encoding graphical marks with schema properties such as required, anyOf, etc. I've managed to get this tool (http://jlblcc.github.io/json-schema-viewer/) working locally but it's no longer being developed, support stops at JSON schema draft4, and the hosted instance doesn't allow me to upload my own schema, it's just a demo. I guess I was drawn in by your stoplight repo of a similar name, thinking it might be the answer. Anyway, maybe a feature for your wishlist. Well done with the rest of spotlight though, it looks great!

**Comment by P0lip** [comment]
> d. I'm looking for a way to graphically visualise a schema, i.e. a tree-like expanding view that allows a reviewer to explore a schema definition, encoding graphical marks with schema properties such as required, anyOf, etc. I

Ah got it. Unfortunately, we don't have anything like that for the time being. :disappointed: 

>  Well done with the rest of spotlight though, it looks great!

Thank you!
