### ISSUE TITLE
Error: l.on is not a function

### ISSUE THREAD

**Issue by Morriz** [stoplightio/json-schema-viewer#90]
## Describe the bug

Just rendering the component with one of the example json files (https://github.com/stoplightio/json-schema-viewer/blob/beta/src/__fixtures__/todo-allof.schema.json) gives the above error.

## To Reproduce

```js
# index.jsx:
const React = require('react')
import schema from './schema.json'
import { JsonSchemaViewer } from '@stoplight/json-schema-viewer'

export default function () {
  return (
    <JsonSchemaViewer
      name='Otomi Values'
      schema={schema}
      expanded={true}
      hideTopBar={false}
      emptyText='No schema defined'
      defaultExpandedDepth={0}
    />
  )
}
```

## Expected behavior

The component to render

## Additional context
**Environment (remove any that are not applicable):**
 - Library version: 2.12.0
 - OS: OSX
 - Browser: Chrome

**Comment by P0lip** [comment]
Hey, I'm terribly sorry for such a delayed response.
We've released new version of JSV, that may fix the issue you're experiencing.
You need to make sure you have the following deps installed
![image](https://user-images.githubusercontent.com/9273484/103241151-a50a6580-4952-11eb-88a0-c1551c2a46cc.png)
Moreover, you'll need to load styles as well. An example stylesheet can be found in our storybook [here](https://github.com/stoplightio/json-schema-viewer/blob/beta/src/__stories__/_styles.scss).

The dependency on Mobx will be removed soon, but it's essential to have it installed for the time being.
