### ISSUE TITLE
@stoplight/lifecycle 

### ISSUE THREAD

**Issue by MatthewAnstey** [stoplightio/json-schema-viewer#94]
## Describe the bug

To get this working I had to add a yarn resolution so  @stoplight/tree-list used "@stoplight/lifecycle": "2.2.1" 

seems to be because of this breaking change in "2.3.1"

https://github.com/stoplightio/lifecycle/commit/fbf004a0e12c9faac11fcb763159accfd751789e#diff-9cb2536ac56d6c39910e37455e7a5be1e0595a10f8470ff4f54f8ff3b59c58a7L107

I was getting createEventEmitter is not a function.

## To Reproduce

These are my dependencies: 
```
	"dependencies": {
		"@stoplight/json-schema-viewer": "^2.12.0",
		"@stoplight/lifecycle": "^2.0.1",
		"@stoplight/markdown-viewer": "^3.5.5",
		"@stoplight/tree-list": "^4.8.0",
		"@stoplight/ui-kit": "^2.10.0",
		"mobx": "^5.13.0",
		"react": "^16.8.0",
		"react-dom": "^16.8.0"
	},
  "resolutions": {
    "@stoplight/lifecycle": "2.2.1"
  }
```

Is there anything i'm doing wrong in my dependencies? 

## Expected behavior

Should not have not use the resolution.

**Environment (remove any that are not applicable):**
 - OS: IOS
 - Browser:Chrome

**Comment by philsturgeon** [comment]
@P0lip any ideas on this one?

**Comment by philsturgeon** [comment]
tree-list has been replaced with https://github.com/stoplightio/json-schema-tree/ so this should no longer be a problem.
